---
- hosts: server2.abc.com
  remote_user: test2000
  become: yes
  tasks:
    - name: Install httpd package
      yum: name=httpd state=installed
    - name: copy index.html
      copy: src=index.html dest=/var/www/html
      notify: restart httpd service
    - name: start http service
      service: name=httpd state=started
  handlers:
    - name: restart httpd service
      service: name=httpd state=restarted
