---
- hosts: webserver 
  remote_user: test2000
  become: yes
  tasks:
    - name: Install httpd package
      yum: name={{item}} state=installed
      with_items:
           - httpd
           - curl
           - telnet
