---
- hosts: server2.abc.com
  remote_user: test2000
  become: yes
  tasks:
    - name: Install httpd package
      command: yum install httpd -y
    - name: copy index.html
      shell: echo "helllo" > /var/www/html/index.html
    - name: start http service
      raw: systemctl start httpd 
    - name: execute script
      script: ./xyz.sh
